object(horde_date)(7) {
  ["year"]=>
  int(2006)
  ["month"]=>
  int(6)
  ["mday"]=>
  int(16)
  ["hour"]=>
  int(18)
  ["min"]=>
  int(0)
  ["sec"]=>
  int(0)
  ["_supportedSpecs"]=>
  string(21) "%CdDeHImMnRStTyYbBpxX"
}
object(horde_date)(7) {
  ["year"]=>
  int(2006)
  ["month"]=>
  int(6)
  ["mday"]=>
  int(17)
  ["hour"]=>
  int(18)
  ["min"]=>
  int(0)
  ["sec"]=>
  int(0)
  ["_supportedSpecs"]=>
  string(21) "%CdDeHImMnRStTyYbBpxX"
}
bool(false)